### PR TITLE
add new instances to python .gitignore

### PR DESCRIPTION
**Pull request by artemMur**

### CODE REVIEW

**Comment by nshmyrev** [comment]
Why is this needed?

**Comment by artemMur** [comment]
> Why is this needed?

New instances prevent git from indexing python environment files such as venv/*, sdist/*. It could improve development experience.

It isn't nessesary, but I supposed it can be useful for people, who develop this project.

**Comment by nshmyrev** [comment]
> python environment files such as venv/, sdist/

We do not have anything like this in our project

**Comment by artemMur** [comment]
> > python environment files such as venv/, sdist/
> 
> We do not have anything like this in our project

Thanks for explanation.

I will close this pr,  due to it's not actual for project.

**Pull request closed without merging**
