### PR TITLE
Build images for Raspberry Pi (armv7hf)

### PR DESCRIPTION
**Pull request by dtreskunov**
This should be backwards-compatible, preserving existing Docker tags:
* alphacep/kaldi-vosk-server
* alphacep/kaldi-{de,cn,en,ru}

While also adding versions with the -rpi suffix:
* alphacep/kaldi-vosk-server-rpi
* alphacep/kaldi-{de,cn,en,ru}-rpi

Language Dockerfiles make use of intermediate build stages to
avoid downloading the same data more than once.

Main Dockerfile is made to build both x86 and ARM binaries by using base
containers from [Balena](https://www.balena.io/docs/reference/base-images/base-images/#building-arm-containers-on-x86-machines) (using QEMU to emulate ARM during the build process).

### CODE REVIEW

**Comment by nshmyrev** [comment]
Hi. Thans a lot for your submission.

RPi works better with openblas instead of atlas. Thats why we build rpi wheel with openblas https://pypi.org/project/vosk/#files

Also, the big models gonna be very slow on rpi,  did you try with mobile models from kaldi-android-demo? They should work almost in realtime.

**Comment by dtreskunov** [comment]
Thanks so much for your response. You are making excellent points!

I'll try the [vosk-api](https://github.com/alphacep/vosk-api) package. Thank you for providing RPi binaries. Do you think it would make sense to use it to build a server similar to kaldi-websocket-python?

I was afraid the models would be too large to run on RPi. Maybe on RPi 4 4GB? I only have a 3B+ to test with.

I see there's a Brazilian Portuguese model [coming to kaldi-android-demo](https://github.com/alphacep/kaldi-android-demo/issues/25). Are there plans to make a lite Russian model available as well? :)

**Comment by nshmyrev** [comment]
On rpi you'd better use vosk-api package, it works with Russian models for Android: https://github.com/alphacep/kaldi-android-demo/releases/tag/2020-01

I don't think even Rpi4 will be able to run server models, you still have to use Android models.

Server has to be updated to use vosk python instead of compiling wrapper directly, I will merge packages soon, a bit of work to properly arranging the code and documenting everything.

**Comment by nshmyrev** [comment]
This one is probably replaced by https://github.com/alphacep/vosk-api/pull/28

**Pull request closed without merging**
